### ISSUE TITLE
Button (1 click) still displayed after iframe is loaded

### ISSUE THREAD

**Issue by bigshit11elf** [hoochicken/mod_qliframe#6]
Hello, in my use case (Joomla 4) the button that displays the iframe is still present after it was clicked. That results in the possibility to click it several times and shows more and more copies of that iframe in the module's position. 

Is that the intended functionality, the result of user error or a bug?

Thank you very much for your module and your support!

**Comment by bigshit11elf** [comment]
Just fyi: 

So far I avoided that problem by hiding the button alltogether and just using the custom image to trigger loading the iframe:

CSS-Code:

.qliframe button {
  display: none;
}

**Comment by hoochicken** [comment]
Hey 11elf ,
Thank you very much for your message.
Your new version is here: https://github.com/hoochicken/mod_qliframe/releases/tag/v1.4.1
Greetings
Mareike Riegel aka The Hoochicken

**Comment by bigshit11elf** [comment]
Thank you very much for your quick reply :)
